@startuml

:<math>int_0^1f(x)dx</math>;
:<math>x^2+y_1+z_12^34</math>;

note right
    Try also
    <math>d/dxf(x)=lim_(h->0)(f(x+h)-f(x))/h</math>
    <latex>P(y|\mathbf{x}) \mbox{ or } f(\mathbf{x})+\epsilon</latex>
end note

@enduml